export interface ITypeSignTrx {
  SEND_TOKEN: 'SEND_TOKEN';
  ADD_OWNER: 'ADD_OWNER';
  REMOVE_OWNER: 'REMOVE_OWNER';
  CHANGE_THRESHOLD: 'CHANGE_THRESHOLD';
  TR_BUILD: 'TRANSACTION_BUILD';
}

export const TYPE_SIGN_TRX: ITypeSignTrx = {
  SEND_TOKEN: 'SEND_TOKEN',
  ADD_OWNER: 'ADD_OWNER',
  REMOVE_OWNER: 'REMOVE_OWNER',
  CHANGE_THRESHOLD: 'CHANGE_THRESHOLD',
  TR_BUILD: 'TRANSACTION_BUILD',
};
