/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as safeDeployments from './safe-deployments';
export type { safeDeployments };
import type * as safeModulesDeployments from './safe-modules-deployments';
export type { safeModulesDeployments };
